#!/usr/bin/env python
# Written by Andrew Drake (adrake@adrake.org), released into the public domain
# The latest version is available at https://github.com/drakedevel/imgurc
import json
import subprocess
import sys

API_URL = 'http://api.imgur.com/2/upload.json'
API_KEY = '5699e23920600c7d178dc30053b238bf'

def do_main():
    if len(sys.argv) <= 1:
        print "Usage: imgurc <image>"
        sys.exit(1)

    response_str = subprocess.check_output(['curl', '-s', '-F', 'key=%s' % API_KEY, '-F', 'image=@%s' % sys.argv[1], API_URL])
    response = json.loads(response_str)
    if response['upload']:
        print('        Image: %s' % response['upload']['links']['original'])
        print('   Imgur Page: %s' % response['upload']['links']['imgur_page'])
        print(' Image Delete: %s' % response['upload']['links']['delete_page'])
    else:
        print('Error: %s' % response['error']['message'])

if __name__ == '__main__':
    do_main()
